language: node_js
node_js:
  - "8.1.4"
before_install:
  - npm update -g npm
install:
  - npm install
script:
  - npm run lint
before_deploy:
  - . build.sh
  - git status
  - git remote -v
  - git config user.name "warriorsword1989"
  - git config user.email "linglong@navinfo.com"
  - git add .
  - git commit -m 'travis automatic generate changelog'
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: WebApp.zip
  skip_cleanup: true
  on:
    tags: true
cache:
  directories:
  - node_modules
branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com:warriorsword1989/travisMain.git
# notifications:
#   slack: navinfo:6troi7FBmywDvUc46jKuSJZE
